apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-service-account-injected
  name: deployment-service-account-injected
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-service-account-injected
  strategy: {}
  template:
    metadata:
      labels:
        app: deployment-service-account-injected
    spec:
      serviceAccountName: service-account-injected
      containers:
      - image: ubuntu
        name: ubuntu
        resources: {}
status: {}
