apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-resource-limits
  name: pod-resource-limits
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    resources: 
      limits:
        cpu: "0.5"
        memory: "0.5Gi"
      requests:
        cpu: "250m"
        memory: "500Mi"

