## Create a pod with two containers wih secrets injected
## echo -n 'mypassword' | base64
apiVersion: v1
kind: Pod
metadata:
  name: two-containers-pod-secret
  labels:
    app: label-app-basic-two-pod-scret
spec:
  containers:
    - name: apache-container
      image: httpd:latest
      envFrom:
        - secretRef:
            name: secret-for-pod
    - name: busy-container
      image: registry.k8s.io/busybox:1.27.2
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; echo "Hello world"; rm -f /tmp/healthy; sleep 600