## Command to get info from etcd 
## ETCDCTL_API=3 etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key get /registry/secrets/default/secret-for-pod | hexdump -c

## To see the secret in etcd 
## ETCDCTL_API=3 etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt --cert=/etc/kubernetes/pki/etcd/server.crt --key=/etc/kubernetes/pki/etcd/server.key get /registry/secrets/default/secret-for-pod | hexdump -c
apiVersion: v1
kind: Secret
metadata:
  name: secret-for-pod
data:
  APP_KEY_NAME: amVmZmVyc29u
  key2: dmFsdWUy
  key3: dmFsdWUz