apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sidecar-pod-label
  name: sidecar-pod
spec:
  containers:
    - image: busybox
      name: pod-busy
      command: ["sleep"]
      args: ["3600"]
      resources: {}
    - image: httpd 
      name: pod-side-httpd
    - image: kodekloud/event-simulator
      name: kodekloud
    - image: kodekloud/filebeat-simulator
      name: filebeat
      volumeMounts: 
      - mountPath: /var/log/event-simulator/
        name: log-volume
  volumes: 
   - name: log-volume
     emptyDir: {}  
status: {}
