apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: parallel-job
  namespace: default
spec:
  completions: 10
  parallelism: 2
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: kodekloud/random-error
        name: random-error
        resources: {}
      restartPolicy: Never
status: {}
