apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-taint
  name: nginx-taint
spec:
  containers:
  - image: nginx
    name: nginx-taint
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations: # Add toleration to the pod
  - key: "spray"
    value: "mortein"
    operator: "Equal"
    effect: "NoSchedule"
